Controllers/ReadingsController.cs
using IsIoTWeb.Models;
using IsIoTWeb.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace IsIoTWeb.Controllers
{
    [Authorize(Roles = "VIEWER,ADMINISTRATOR")]
    public class ReadingsController : Controller
    {
        private IReadingRepository _readingRepository;

        public ReadingsController(IReadingRepository readingRepository)
        {
            _readingRepository = readingRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetReadingsByFilter([FromBody] ReadingFilter? filter)
        {
            if (filter == null)
            {
                return Json(new Error() { ErrorMessages = { "Filter is null!" } });
            }

            try
            {
                return Json(_readingRepository.GetAllByFilter(filter).Result.ToList());
            }
            catch (Exception)
            {
                return Json(new Error() { ErrorMessages = { "An error occured when fetching collectors' data!" } });
            }
        }

        [HttpGet]
        public ActionResult Details(string id)
        {
            return View(new ReadingFilter() { CollectorId = id });
        }
    }
}

Controllers/RolesController.cs
using IsIoTWeb.Models;
using IsIoTWeb.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace IsIoTWeb.Controllers
{
    [Authorize(Roles = "ADMINISTRATOR")]
    public class RolesController : Controller
    {
        private IRoleRepository _roleRepository;

        public RolesController( IRoleRepository roleRepository)
        {
            _roleRepository = roleRepository;
        }

        public IActionResult Index()
        {
            List<Role> roles = new List<Role>();
            try
            {
                roles = (List<Role>)_roleRepository.GetAll().Result;
            }
            catch (Exception)
            {
                /* Do nothing. Return empty list of roles. */
            }
            return View(roles);
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create([Required] string name)
        {
            if (ModelState.IsValid)
            {
                List<string> errors = new List<string>();
                try
                {
                    errors = await _roleRepository.Create(name);
                }
                catch (Exception)
                {
                    return RedirectToAction("Index");
                }

                if (errors == null)
                {
                    ViewBag.Message = "Role Created Successfully";
                }
                else
                {
                    foreach (string error in errors)
                    {
                        ModelState.AddModelError("", error);
                    }
                }
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            try
            {
                await _roleRepository.Delete(id);
            }
            catch (Exception)
            {
                /* Do nothing. Return to index. */
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/UsersController.cs
using IsIoTWeb.Models;
using IsIoTWeb.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IsIoTWeb.Controllers
{
    [Authorize(Roles = "ADMINISTRATOR")]
    public class UsersController : Controller
    {
        private IUserRepository _userRepository;
        private IRoleRepository _roleRepository;
        private ISinkRepository _sinkRepository;

        public UsersController(IUserRepository userRepository, IRoleRepository roleRepository, ISinkRepository sinkRepository)
        {
            _userRepository = userRepository;
            _roleRepository = roleRepository;
            _sinkRepository = sinkRepository;
        }

        public IActionResult Index() => View();

        public async Task<ViewResult> Create()
        {
            try
            {
                List<Role> roleList = (List<Role>)await _roleRepository.GetAll();
                ViewBag.Roles = roleList;
            }
            catch (Exception)
            {
                ViewBag.Errors = "An error occured when fetching user's roles data!";
            }
            return View();
        }

        public ViewResult Details() => View();

        public async Task<ViewResult> Edit()
        {
            try
            {
                List<Role> roleList = (List<Role>)await _roleRepository.GetAll();
                ViewBag.Roles = roleList;
            }
            catch (Exception)
            {
                ViewBag.Errors = "An error occured when fetching user's roles data!";
            }
            return View();
        }

        public ActionResult GetUsers()
        {
            List<UserPresentation> userPresentations = new List<UserPresentation>();
            try
            {
                List<User> users = (List<User>)_userRepository.GetAll().Result;
                foreach(var user in users)
                {
                    var roleObjectId = user.Roles.FirstOrDefault();
                    userPresentations.Add( new UserPresentation()
                    {
                        Id = Utils.Utils.DynamicObjectIdToString(user.Id.Timestamp, user.Id.Machine, user.Id.Pid, user.Id.Increment),
                        Username = user.UserName,
                        FirstName = user.FirstName,
                        LastName = user.LastName,
                        Email = user.Email,
                        CreatedOn = user.CreatedOn.ToString(),
                        PhoneNumber = user.PhoneNumber,
                        Role = GetRoleName(Utils.Utils.DynamicObjectIdToString(roleObjectId.Timestamp, roleObjectId.Machine, roleObjectId.Pid, roleObjectId.Increment))
                    });
                }
            }
            catch (Exception)
            {
                return Json(new Error() { ErrorMessages = { "An error occured when fetching Users' data!" } });
            }
            return Json(userPresentations);
        }

        [HttpPost]
        public async Task<IActionResult> Create(UserCreateInput userCreateInput)
        {
            if (ModelState.IsValid)
            {
                List<string> errors = new List<string>();
                try
                {
                    errors = await _userRepository.Create(userCreateInput);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(userCreateInput);
                }

                try
                {
                    var user = _userRepository.GetByUsername(userCreateInput.Username);
                    await _sinkRepository.AddUser(user.Id.ToString());
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(userCreateInput);
                }

                if (errors != null)
                {
                    foreach (string error in errors)
                    {
                        ModelState.AddModelError("", error);
                    }
                    return View(userCreateInput);
                }
            }
            else
            {
                return View(userCreateInput);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult GetId([FromBody] UserDynamicId id)
        {
            return Json(new { id = Utils.Utils.DynamicObjectIdToString(id.Timestamp, id.Machine, id.Pid, id.Increment) });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            User user;
            UserUpdateInput userUpdateInput = new UserUpdateInput();
            try
            {
                user = await _userRepository.Get(id);
                userUpdateInput.FirstName = user.FirstName;
                userUpdateInput.LastName = user.LastName;
                userUpdateInput.Email = user.Email;
                userUpdateInput.PhoneNumber = user.PhoneNumber;
                userUpdateInput.Username = user.UserName;
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }

            return View(userUpdateInput);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            User user;
            UserPresentation userPresenation;
            try
            {
                user = await _userRepository.Get(id);
                var roleObjectId = user.Roles.FirstOrDefault();
                userPresenation = new UserPresentation()
                {
                    Id = Utils.Utils.DynamicObjectIdToString(user.Id.Timestamp, user.Id.Machine, user.Id.Pid, user.Id.Increment),
                    Username = user.UserName,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    Email = user.Email,
                    CreatedOn = user.CreatedOn.ToString(),
                    PhoneNumber = user.PhoneNumber,
                    Role = GetRoleName(Utils.Utils.DynamicObjectIdToString(roleObjectId.Timestamp, roleObjectId.Machine, roleObjectId.Pid, roleObjectId.Increment))
                };
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }

            return View(userPresenation);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            try
            {
                await _userRepository.Delete(id);
            }
            catch (Exception)
            {
                /* Do nothing. Return to index. */
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserUpdateInput userUpdateInput)
        {
            if (ModelState.IsValid)
            {
                List<string> errors = new List<string>();
                try
                {
                    errors = await _userRepository.Update(userUpdateInput);
                }
                catch (Exception)
                {
                    return RedirectToAction("Index");
                }

                if (errors == null)
                {
                    ViewBag.Message = "User Updated Successfully";
                }
                else
                {
                    foreach (string error in errors)
                    {
                        ModelState.AddModelError("", error);
                    }
                    return View(userUpdateInput);
                }
            }
            else
            {
                return View(userUpdateInput);
            }
            return RedirectToAction("Index");
        }
        
        private string GetRoleName(string id)
        {
            return _roleRepository.Get(id).Result.Name;
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>IoT Irrigation System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IoT Irrigation System</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @{
                        if (User?.Identity?.IsAuthenticated ?? false)
                        {
                            <ul class="navbar-nav flex-grow-1">

                                @{
                                    if (User?.IsInRole("ADMINISTRATOR") ?? false)
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Readings" asp-action="Index">Readings</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                                        </li>
                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" asp-area="" asp-controller="Irrigation" asp-action="Index">
                                                Irrigation
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                                <a class="dropdown-item" asp-area="" asp-controller="Irrigation" asp-action="Logs">Logs</a>
                                                <a class="dropdown-item" asp-area="" asp-controller="Irrigation" asp-action="Manual">Manual</a>
                                                <a class="dropdown-item" asp-area="" asp-controller="Irrigation" asp-action="Scheduled">Scheduled</a>
                                                <a class="dropdown-item" asp-area="" asp-controller="Irrigation" asp-action="Automated">Automated</a>
                                                <a class="dropdown-item" asp-area="" asp-controller="Irrigation" asp-action="Configure">Configure</a>
                                            </div>
                                        </li>
                                    }

                                    if (User?.IsInRole("VIEWER") ?? false)
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Readings" asp-action="Index">Readings</a>
                                        </li>
                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" asp-area="" asp-controller="Irrigation" asp-action="Index">
                                                Irrigation
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                                <a class="dropdown-item" asp-area="" asp-controller="Irrigation" asp-action="Automated">Automated</a>
                                            </div>
                                        </li>
                                    }
                                }
                            </ul>
                            //<span class="align-middle mx-auto" style="width: 75px;">Welcome @User.Identity.Name</span>
                            <a asp-controller="Account" asp-action="Logout" class="btn btn-danger">Logout</a>
                        }
                        else
                        {
                            <a asp-controller="Account" asp-action="Login">Log in</a>
                        }
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - IoT Irrigation System - made with &#10084;&#65039; by Daniel Popa
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>